# Generated by Django 2.0.3 on 2018-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='move_count',
            field=models.IntegerField(default=0),
        ),
    ]
